In [18]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [2]:
start_time = time.time()
#matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


0.00223613


In [3]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

# Start the timer for PyTorch matrix multiplication
start_time = time.time()

rand = (torch_rand1 @ torch_rand2)
# Record the end time for PyTorch matrix multiplication
end_time = time.time()

# Calculate and print the elapsed time for PyTorch matrix multiplication
elapsed_time = end_time - start_time
print(f"PyTorch elapsed time: {elapsed_time:.8f} seconds")

start_time = time.time()
rand = np


PyTorch elapsed time: 0.42929173 seconds


In [4]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")


0.00018287
CPU times: user 156 µs, sys: 101 µs, total: 257 µs
Wall time: 247 µs


In [5]:
probabilities = torch.tensor([0.1, 0.9])
samples = torch.multinomial(probabilities, num_samples=50, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1])


In [6]:
tensor = torch.tensor([1, 2, 3, 4])
out =torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [7]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [8]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [12]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [13]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [16]:
# Import the neural network module from PyTorch
import torch.nn as nn

# Create a sample tensor with three elements, each of value 10.0.
# This will be the input to our neural network layer.
sample = torch.tensor([10., 10., 10.])

# Initialize a linear layer (fully connected layer) where:
# - The first argument (3) is the size of each input sample (number of input features).
# - The second argument (3) is the size of each output sample (number of output features).
# - The 'bias=False' argument means that we are not using a bias term in our linear calculations.
linear = nn.Linear(3, 3, bias=False)

# Apply the linear layer to our input sample.
# The operation performed here is a matrix multiplication of the input 'sample' with the layer's internal weight matrix.
# Since bias is False, there will be no bias term added to the result.
output = linear(sample)

# Print the output tensor.
print(output)


tensor([  4.4400,   5.4171, -14.7660], grad_fn=<SqueezeBackward4>)


In [20]:
import torch.nn.functional as F
#Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

#Aplly softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [29]:
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

input_indices =torch.LongTensor([1, 5, 3, 2])

embedded_output = embedding(input_indices)

print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[-0.4677, -2.2848,  0.0659, -0.1024,  0.1038, -0.2594],
        [-0.5352, -1.3623,  0.5582,  0.3839,  0.7814,  0.3249],
        [-0.9195, -0.1365,  0.0246, -0.8381, -1.0781,  0.1159],
        [ 0.9649,  0.2591,  0.2790,  1.3447, -0.7193, -1.0317]],
       grad_fn=<EmbeddingBackward0>)


In [31]:
a = torch.tensor([[1, 2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [35]:
int_64 = torch.randint(1, (3,2)).float()
float_32 = torch.rand(2,3)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
